# Introdução
Aqui nos conseguimos configurar alguns parametros de como queremos que seja feito o funcionamento do pandas. Por exemplo podemos colocar quantas `linhas`, `colunas` ver por padrão ao rodar algo como:
```python
df
```
Podemos colocar também para que esse display na tela arredonde as colunas float para ser facil a visualização mas sem alterar os valores das colunas, é apenas para melhor visualização.
Por exemplo temos uma coluna com valor *0.93932421* mas queremos olhar ela através do Display no `jupyter` podemos configurar o display para arredondar esse numero em 3 casas decimais e veriamos algo como *0.939*. Mas ao fazer contas com esse valor ele ainda usaria o valor padrão dele *0.93932421*.

Todos essas configurações podem ser feitas olhando as opções que o **pandas** nos permite mexer:
```python
import pandas as pd

pd.describe_option()
```

In [38]:
import pandas as pd
import numpy as np

In [37]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: True]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table, or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: 20]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 80]
future.infer_string Whether to infer sequence of str objects as pyarrow string dtype, which will be the default in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
future.no_silent_downcasting Whether to opt-in to the future behavior which will *not* silently downcast results from Series and DataFrame `where`, `mask`, and `clip` methods. Silent downcasting will be removed in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf, calamine.
    [default: auto] [currently: auto]
io.excel.ods.writer : string
    The default Excel writer engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd, calamine.
    [default: auto] [currently: auto]
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
io.sql.engine : string
    The default sql reader/writer engine. Available options:
    'auto', 'sqlalchemy', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.copy_on_write : bool
    Use new copy-view behaviour using Copy-on-Write. Defaults to False,
    unless overridden by the 'PANDAS_COPY_ON_WRITE' environment variable
    (if set to "1" for True, needs to be set before pandas is imported).
    [default: False] [currently: False]
mode.data_manager : string
    Internal data manager type; can be "block" or "array". Defaults to "block",
    unless overridden by the 'PANDAS_DATA_MANAGER' environment variable (needs
    to be set before pandas is imported).
    [default: block] [currently: block]
    (Deprecated, use `` instead.)
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: False]
mode.string_storage : string
    The default storage for StringDtype.
    [default: auto] [currently: auto]
mode.use_inf_as_na : boolean
    True means treat None, NaN, INF, -INF as NA (old way),
    False means None and NaN are null, but INF, -INF are not NA
    (new way).

    This option is deprecated in pandas 2.1.0 and will be removed in 3.0.
    [default: False] [currently: False]
    (Deprecated, use `` instead.)
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    providing the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]
styler.format.decimal : str
    The character representation for the decimal separator for floats and complex.
    [default: .] [currently: .]
styler.format.escape : str, optional
    Whether to escape certain characters according to the given context; html or latex.
    [default: None] [currently: None]
styler.format.formatter : str, callable, dict, optional
    A formatter object to be used as default within ``Styler.format``.
    [default: None] [currently: None]
styler.format.na_rep : str, optional
    The string representation for values identified as missing.
    [default: None] [currently: None]
styler.format.precision : int
    The precision for floats and complex numbers.
    [default: 6] [currently: 6]
styler.format.thousands : str, optional
    The character representation for thousands separator for floats, int and complex.
    [default: None] [currently: None]
styler.html.mathjax : bool
    If False will render special CSS classes to table attributes that indicate Mathjax
    will not be used in Jupyter Notebook.
    [default: True] [currently: True]
styler.latex.environment : str
    The environment to replace ``\begin{table}``. If "longtable" is used results
    in a specific longtable environment format.
    [default: None] [currently: None]
styler.latex.hrules : bool
    Whether to add horizontal rules on top and bottom and below the headers.
    [default: False] [currently: False]
styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
    The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
    decorators can also be added to non-naive values to draw vertical
    rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
    [default: r] [currently: r]
styler.latex.multirow_align : {"c", "t", "b"}
    The specifier for vertical alignment of sparsified LaTeX multirows.
    [default: c] [currently: c]
styler.render.encoding : str
    The encoding used for output HTML and LaTeX files.
    [default: utf-8] [currently: utf-8]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.max_elements : int
    The maximum number of data-cell (<td>) elements that will be rendered before
    trimming will occur over columns, rows or both if needed.
    [default: 262144] [currently: 262144]
styler.render.max_rows : int, optional
    The maximum number of rows that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.repr : str
    Determine which output to use in Jupyter Notebook in {"html", "latex"}.
    [default: html] [currently: html]
styler.sparse.columns : bool
    Whether to sparsify the display of hierarchical columns. Setting to False will
    display each explicit level element in a hierarchical key for each column.
    [default: True] [currently: True]
styler.sparse.index : bool
    Whether to sparsify the display of a hierarchical index. Setting to False will
    display each explicit level element in a hierarchical key for each row.
    [default: True] [currently: True]

In [61]:
df = pd.DataFrame(
    np.random.rand(100, 25),
    columns=[f"col_{i+1}" for i in range(25)]
)

In [62]:
# Ele mostra 10 linhas e 20 colunas (10 primeiras e 10 ultimas) por padrão
df

    col_1  col_2  ...  col_24  col_25
0     0.1    0.5  ...     0.9     0.8
1     0.7    0.2  ...     0.2     0.5
..    ...    ...  ...     ...     ...
98    0.6    0.5  ...     0.7     0.7
99    0.9    0.6  ...     0.2     0.7

[100 rows x 25 columns]

In [63]:
pd.set_option("display.max_rows", 4)  # qtde de linhas mostradas (o limite é 10)
pd.set_option("display.max_columns", 4)  # qtde de colunas mostradas
pd.set_option("display.float_format", "{:.1f}".format)  # display das colunas float (não altera o número em sí apenas a visualização)

In [64]:
df

    col_1  col_2  ...  col_24  col_25
0     0.1    0.5  ...     0.9     0.8
1     0.7    0.2  ...     0.2     0.5
..    ...    ...  ...     ...     ...
98    0.6    0.5  ...     0.7     0.7
99    0.9    0.6  ...     0.2     0.7

[100 rows x 25 columns]

In [69]:
pd.set_option("display.max_rows", None)  # mostra todas as linhas
pd.set_option("display.max_columns", None)  # mostra todas as colunas

In [70]:
df

,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15,col_16,col_17,col_18,col_19,col_20,col_21,col_22,col_23,col_24,col_25
0,0.098456,0.535637,0.458692,0.868133,0.159866,0.068098,0.013720,0.552712,0.773944,0.130788,0.459266,0.464183,0.124310,0.613902,0.179902,0.363725,0.014331,0.145128,0.900499,0.154200,0.862587,0.714738,0.500876,0.893423,0.827683
1,0.666551,0.199129,0.113908,0.210120,0.906292,0.705294,0.088237,0.258326,0.939174,0.540132,0.012652,0.134419,0.597335,0.191123,0.928717,0.839374,0.272497,0.036057,0.093916,0.438405,0.282779,0.954644,0.788169,0.177984,0.453759
2,0.656975,0.755802,0.061194,0.709328,0.790547,0.920393,0.785355,0.933094,0.031755,0.430484,0.638767,0.249879,0.039344,0.575312,0.255209,0.691620,0.695630,0.329219,0.936155,0.942365,0.626486,0.152185,0.853133,0.301353,0.318562
3,0.189837,0.673615,0.065945,0.664920,0.021058,0.919143,0.675001,0.739302,0.566167,0.819979,0.321102,0.291758,0.054295,0.411054,0.526205,0.382811,0.553252,0.573448,0.709384,0.915707,0.947968,0.993401,0.958356,0.480183,0.712311
4,0.230764,0.597503,0.302457,0.346512,0.059277,0.446300,0.128191,0.044563,0.633335,0.805341,0.799948,0.953584,0.718905,0.070383,0.643653,0.387274,0.506204,0.621079,0.266936,0.883223,0.029511,0.311366,0.528980,0.841551,0.775268
5,0.887441,0.349539,0.228248,0.269461,0.131403,0.547778,0.884283,0.993226,0.975129,0.990453,0.901789,0.153630,0.158782,0.857638,0.553911,0.518763,0.370220,0.020564,0.734126,0.314030,0.821125,0.470523,0.352492,0.636726,0.569614
6,0.146962,0.417629,0.024184,0.968802,0.052236,0.294459,0.074370,0.920987,0.455002,0.129123,0.157742,0.029481,0.767932,0.107415,0.047771,0.330476,0.042924,0.670995,0.489163,0.698484,0.599961,0.012251,0.187572,0.028050,0.657599
7,0.649302,0.192085,0.882049,0.171321,0.411247,0.553084,0.319491,0.432634,0.449208,0.943964,0.007955,0.614583,0.644597,0.961801,0.719401,0.931906,0.156490,0.513649,0.277306,0.138133,0.157682,0.442331,0.942014,0.973545,0.975325
8,0.714774,0.671940,0.378744,0.227162,0.208503,0.266144,0.434774,0.923759,0.703041,0.461115,0.404215,0.168176,0.469553,0.915162,0.403660,0.207254,0.004759,0.662580,0.286877,0.345719,0.364496,0.517845,0.518643,0.622090,0.996817
9,0.899713,0.003093,0.297193,0.487336,0.268866,0.487624,0.574133,0.252977,0.349466,0.889095,0.258234,0.331203,0.351983,0.017108,0.207531,0.538230,0.614729,0.358527,0.659066,0.299232,0.067722,0.622053,0.639264,0.291248,0.341109
10,0.671928,0.486489,0.715303,0.694916,0.801722,0.965937,0.233808,0.014116,0.279271,0.973810,0.716875,0.507993,0.720580,0.214876,0.577328,0.617303,0.456298,0.652716,0.573808,0.455426,0.516113,0.954091,0.001263,0.444049,0.208897
11,0.812488,0.439047,0.853265,0.942843,0.577011,0.940436,0.780725,0.795931,0.255208,0.960547,0.909812,0.276443,0.850509,0.284124,0.645667,0.197584,0.562233,0.150651,0.514079,0.843260,0.754912,0.628812,0.077884,0.044339,0.913150
12,0.844356,0.154377,0.385230,0.506996,0.825335,0.917982,0.202698,0.053241,0.658174,0.630092,0.339459,0.749275,0.724428,0.660775,0.813747,0.854417,0.846592,0.698516,0.072720,0.955308,0.306511,0.799172,0.958984,0.732392,0.967280
13,0.796647,0.384670,0.123838,0.899642,0.391878,0.725596,0.177667,0.481059,0.928643,0.500348,0.033342,0.097556,0.968593,0.318169,0.389886,0.182907,0.735050,0.642948,0.353456,0.074662,0.552115,0.885696,0.678518,0.735616,0.368487
14,0.709105,0.973223,0.246452,0.286988,0.058997,0.643732,0.330861,0.256327,0.608798,0.003275,0.517106,0.605215,0.743114,0.297482,0.606640,0.901664,0.669949,0.107319,0.374151,0.560243,0.018007,0.422691,0.970556,0.186639,0.568240
15,0.951676,0.508049,0.442053,0.849896,0.307649,0.311360,0.325116,0.006176,0.909064,0.591195,0.079033,0.122029,0.195170,0.346191,0.393043,0.848453,0.933866,0.985866,0.510934,0.995669,0.438112,0.399889,0.240593,0.871067,0.839169
16,0.957334,0.454939,0.982910,0.184457,0.446748,0.328081,0.465098,0.569882,0.832645,0.752058,0.882554,0.571881,0.187756,0.175813,0.847063,0.667173,0.426734,0.024339,0.829517,0.144263,0.113693,0.503390,0.160118,0.326075,0.913758
17,0.652906,0.062259,0.474366,0.549352,0.039094,0.632029,0.980201,0.957583,0.032085,0.906335,0.900793,0.933014,0.194085,0.059333,0.076887,0.129243,0.442337,0.458275,0.073387,0.606344,0.490296,0.033420,0.760886,0.373046,0.147648
18,0.577343,0.993883,0.920304,0.643270,0.836362,0.763472,0.757518,0.934831,0.537735,0.128875,0.978050,0.995622,0.394157,0.622970,0.667733,0.051590,0.246820,0.932921,0.074448,0.736357,0.401212,0.464101,0.071816,0.956663,0.719366
19,0.504757,0.514264,0.613583,0.537367,0.841342,0.697863,0.178665,0.786949,0.348524,0.754077,0.747308,0.079654,0.999098,0.818838,0.056190,0.595367,0.234010,0.762742,0.494665,0.400011,0.687704,0.011140,0.515133,0.664511,0.410826
20,0.383668,0.338752,0.654400,0.264687,0.359894,0.134659,0.161768,0.107777,0.906410,0.683967,0.847036,0.979273,0.005835,0.029847,0.369733,0.474993,0.832066,0.147892,0.148643,0.445325,0.269820,0.230920,0.178107,0.083326,0.740178
21,0.678175,0.375728,0.195637,0.999393,0.149496,0.669406,0.588375,0.445074,0.919490,0.141775,0.067647,0.847464,0.710466,0.500120,0.386533,0.063297,0.934018,0.410334,0.635752,0.544834,0.849543,0.212427,0.086227,0.320746,0.513090
22,0.189252,0.271433,0.869374,0.298394,0.003512,0.291410,0.704004,0.251840,0.393289,0.485710,0.181803,0.260628,0.963825,0.910092,0.072407,0.979613,0.136885,0.146559,0.464415,0.008161,0.491411,0.237036,0.472016,0.731749,0.350297
23,0.930188,0.140184,0.003066,0.277948,0.794505,0.153476,0.238161,0.951553,0.309592,0.315313,0.540686,0.581995,0.248441,0.025671,0.295949,0.616705,0.863906,0.484552,0.608600,0.987008,0.220905,0.516018,0.306366,0.873952,0.176426
24,0.985163,0.611752,0.751934,0.702576,0.196519,0.699261,0.905556,0.684272,0.185211,0.496422,0.894395,0.479830,0.361968,0.587365,0.316942,0.479019,0.862075,0.976612,0.440583,0.447316,0.545648,0.260723,0.105315,0.229163,0.690147
25,0.644895,0.919611,0.875511,0.907335,0.284161,0.813119,0.081307,0.520164,0.713082,0.663287,0.206549,0.312650,0.255641,0.379448,0.073239,0.839508,0.181660,0.348610,0.452302,0.460522,0.914229,0.966767,0.060479,0.474434,0.493843
26,0.834241,0.991956,0.089123,0.329845,0.119055,0.199475,0.485630,0.704136,0.486334,0.751246,0.443562,0.471614,0.481748,0.382014,0.739669,0.166834,0.038007,0.042840,0.724620,0.207224,0.870038,0.723750,0.431143,0.308363,0.631861
27,0.080210,0.676277,0.033617,0.775591,0.002617,0.793134,0.992310,0.815150,0.619820,0.046614,0.690677,0.590152,0.097870,0.687604,0.379212,0.219645,0.718231,0.031196,0.776450,0.020407,0.114072,0.726126,0.842261,0.767551,0.830397
28,0.666835,0.859334,0.420026,0.141496,0.635040,0.070258,0.943922,0.414487,0.368147,0.509021,0.330643,0.564802,0.390387,0.882190,0.838624,0.331902,0.433897,0.570027,0.003060,0.360105,0.431058,0.959304,0.955547,0.001591,0.474167
29,0.508920,0.225621,0.880142,0.538051,0.463640,0.761812,0.122375,0.409375,0.968871,0.928393,0.736166,0.251091,0.631708,0.636546,0.722357,0.140726,0.931268,0.837733,0.936929,0.990392,0.470474,0.257881,0.342720,0.066769,0.050631
30,0.911505,0.843491,0.955356,0.962507,0.546227,0.657794,0.381672,0.259556,0.946314,0.837565,0.337512,0.959150,0.016107,0.004451,0.106694,0.399107,0.010378,0.100267,0.163378,0.997877,0.835637,0.658750,0.532588,0.995797,0.954807
31,0.257303,0.904854,0.483563,0.550891,0.611930,0.762250,0.090691,0.643371,0.207734,0.248693,0.018674,0.632532,0.692314,0.768050,0.741890,0.637021,0.179347,0.313678,0.308362,0.022625,0.833392,0.764117,0.280879,0.346051,0.458341
32,0.572595,0.167891,0.824809,0.127575,0.332534,0.354160,0.669833,0.418656,0.376543,0.926513,0.130573,0.373025,0.807055,0.848976,0.041542,0.568256,0.494846,0.910097,0.208132,0.445059,0.539892,0.764837,0.994883,0.922627,0.792846
33,0.480034,0.594693,0.938266,0.827312,0.296635,0.142676,0.269345,0.971922,0.384877,0.871933,0.826774,0.663668,0.939599,0.220810,0.290063,0.221456,0.713432,0.037291,0.749902,0.896821,0.315032,0.474382,0.168711,0.052629,0.355432
34,0.625346,0.676372,0.822113,0.463412,0.006525,0.124627,0.833612,0.533809,0.889451,0.488218,0.107827,0.075044,0.601669,0.393201,0.731067,0.840569,0.159937,0.301217,0.050402,0.734715,0.273777,0.586535,0.135620,0.508955,0.040561
35,0.388138,0.371910,0.244703,0.995692,0.114588,0.024306,0.055557,0.127571,0.551014,0.443888,0.209536,0.380097,0.901003,0.605430,0.008155,0.758767,0.548613,0.256299,0.478461,0.331810,0.621625,0.223317,0.535680,0.415540,0.669976
36,0.822460,0.040178,0.468442,0.799203,0.682987,0.958656,0.567463,0.456256,0.135298,0.747903,0.385051,0.760564,0.341897,0.177229,0.162218,0.842248,0.199520,0.670230,0.846391,0.209680,0.860236,0.780051,0.331048,0.806881,0.207524
37,0.568931,0.355969,0.327310,0.789077,0.890759,0.544436,0.509344,0.122545,0.992524,0.485875,0.323540,0.812978,0.263790,0.334304,0.950562,0.758512,0.236984,0.931553,0.921192,0.985286,0.488842,0.217480,0.898286,0.602061,0.322370
38,0.259869,0.946434,0.422957,0.480913,0.418790,0.802246,0.884416,0.181626,0.374022,0.026724,0.012801,0.057788,0.473334,0.912764,0.877568,0.401921,0.467214,0.637812,0.494719,0.728017,0.559289,0.348998,0.944863,0.530040,0.733755
39,0.460168,0.938024,0.232862,0.686561,0.640579,0.134815,0.536981,0.120166,0.873548,0.701938,0.505740,0.983197,0.299581,0.851240,0.998464,0.545346,0.003170,0.832693,0.159485,0.659556,0.499266,0.929817,0.293720,0.652993,0.734779
40,0.296287,0.552640,0.096204,0.542779,0.000438,0.085872,0.087945,0.581676,0.885672,0.617351,0.271868,0.306347,0.240751,0.154939,0.251487,0.524057,0.507279,0.507406,0.745519,0.167590,0.161341,0.184429,0.818772,0.953703,0.962654
41,0.678253,0.893261,0.613611,0.960484,0.306716,0.829311,0.204707,0.913731,0.852271,0.067802,0.968558,0.542342,0.263365,0.263035,0.963816,0.131392,0.060790,0.512230,0.928411,0.816009,0.744725,0.272512,0.220789,0.224637,0.535426
42,0.525327,0.893795,0.890618,0.630275,0.039383,0.105676,0.746503,0.637062,0.845972,0.097528,0.683832,0.574415,0.190020,0.913485,0.403640,0.243065,0.939384,0.524927,0.339608,0.810246,0.199759,0.811534,0.024691,0.442515,0.896816
43,0.127840,0.147394,0.187171,0.002334,0.719764,0.129798,0.577710,0.802030,0.751787,0.505923,0.376105,0.469598,0.175986,0.279114,0.666420,0.869176,0.659391,0.628394,0.335877,0.720401,0.143321,0.922999,0.522672,0.622400,0.294533
44,0.453297,0.320210,0.683132,0.918202,0.053690,0.111545,0.121876,0.120283,0.204492,0.594532,0.824934,0.659101,0.286487,0.414444,0.338188,0.312696,0.219669,0.226496,0.768318,0.301985,0.716342,0.807989,0.962576,0.763305,0.819600
45,0.165836,0.117402,0.877467,0.038020,0.943329,0.827718,0.907761,0.081478,0.207650,0.006616,0.771623,0.012701,0.797527,0.277510,0.992179,0.381793,0.651029,0.514868,0.344918,0.105602,0.737272,0.598938,0.278711,0.579186,0.456195
46,0.552709,0.955050,0.615302,0.330133,0.983330,0.273129,0.881118,0.358769,0.888727,0.259808,0.346377,0.457504,0.027088,0.470283,0.684086,0.568556,0.055944,0.971001,0.332003,0.215591,0.303161,0.195874,0.542973,0.327559,0.750778
47,0.156079,0.544718,0.687379,0.102006,0.095601,0.812579,0.722288,0.384814,0.195133,0.035567,0.052974,0.053199,0.600446,0.741069,0.708576,0.408125,0.051412,0.233653,0.806472,0.375936,0.040365,0.001832,0.690775,0.619803,0.418002
48,0.055896,0.869940,0.994470,0.482990,0.545528,0.162402,0.918185,0.670252,0.902485,0.524760,0.131021,0.111409,0.751269,0.770085,0.071028,0.451737,0.156005,0.039674,0.103192,0.852499,0.899457,0.670871,0.401976,0.874479,0.215028
49,0.795733,0.413324,0.974752,0.725668,0.911488,0.278235,0.620955,0.352872,0.530685,0.226204,0.117762,0.839150,0.841718,0.810447,0.021335,0.068742,0.898240,0.759266,0.715183,0.022962,0.296361,0.184502,0.374004,0.175985,0.725089
50,0.076601,0.066148,0.555297,0.119061,0.686985,0.158968,0.924217,0.564873,0.017517,0.295625,0.671411,0.931111,0.199545,0.664418,0.631780,0.296960,0.279835,0.091568,0.300706,0.831383,0.309705,0.168613,0.812520,0.952284,0.833617
51,0.366847,0.913415,0.268005,0.972748,0.794385,0.072460,0.703419,0.981957,0.128180,0.313479,0.910314,0.101214,0.554996,0.952133,0.602905,0.845567,0.991580,0.485543,0.905126,0.873129,0.589110,0.491422,0.781375,0.778623,0.536120
52,0.790330,0.603532,0.156822,0.971310,0.187316,0.695238,0.882274,0.911250,0.827974,0.381031,0.625272,0.563344,0.560624,0.623220,0.504955,0.601284,0.168914,0.399310,0.471434,0.194414,0.370172,0.780739,0.863818,0.481318,0.732266
53,0.675796,0.774062,0.428344,0.817332,0.411907,0.154313,0.773536,0.800011,0.295203,0.616419,0.574824,0.329845,0.438062,0.555053,0.836908,0.233188,0.344773,0.391243,0.576472,0.686259,0.564949,0.728050,0.378853,0.218295,0.881320
54,0.955870,0.643378,0.635637,0.958465,0.108368,0.616347,0.120115,0.659341,0.702859,0.606997,0.140987,0.819913,0.385107,0.546423,0.901978,0.063482,0.728062,0.570473,0.034696,0.401040,0.766053,0.365434,0.852963,0.814252,0.530600
55,0.436702,0.084832,0.729319,0.281500,0.829239,0.644053,0.647434,0.081706,0.246248,0.088173,0.839425,0.309977,0.149268,0.955185,0.565622,0.282385,0.277072,0.844304,0.497476,0.156220,0.993225,0.361314,0.580471,0.167945,0.946338
56,0.657038,0.326013,0.850237,0.475575,0.913360,0.290209,0.064431,0.180371,0.387170,0.902628,0.557563,0.373818,0.923112,0.432714,0.952433,0.729746,0.658490,0.712524,0.126779,0.664933,0.046863,0.004218,0.341294,0.491927,0.911452
57,0.438438,0.775531,0.408730,0.960478,0.343744,0.605806,0.364540,0.904059,0.244443,0.675114,0.765226,0.082996,0.804088,0.439805,0.684897,0.137126,0.038581,0.452625,0.404003,0.832389,0.712029,0.162200,0.381585,0.116388,0.618107
58,0.330512,0.865171,0.712512,0.809866,0.586795,0.850916,0.569180,0.479248,0.043831,0.324570,0.537560,0.907021,0.149357,0.083164,0.933976,0.829160,0.291441,0.444528,0.343595,0.896695,0.147204,0.445531,0.567468,0.393933,0.385526
59,0.942226,0.527180,0.681849,0.739178,0.103598,0.100040,0.729152,0.457368,0.836168,0.898708,0.252739,0.411129,0.870432,0.884413,0.903483,0.601012,0.346870,0.946392,0.711054,0.683700,0.100268,0.951119,0.187123,0.886830,0.125652
60,0.231496,0.890038,0.743209,0.641200,0.578989,0.602521,0.754929,0.794926,0.306978,0.983178,0.613241,0.346049,0.774358,0.519516,0.495554,0.508648,0.112008,0.189141,0.869890,0.816561,0.724775,0.879898,0.693840,0.325149,0.281797
61,0.516242,0.223952,0.505151,0.378616,0.525387,0.621384,0.054753,0.230849,0.226477,0.623175,0.272397,0.313302,0.144172,0.679866,0.604361,0.794678,0.067432,0.300632,0.053123,0.466246,0.273741,0.345561,0.588469,0.640411,0.799474
62,0.623309,0.262434,0.597925,0.657653,0.596245,0.760666,0.838238,0.842665,0.703267,0.691288,0.038025,0.875920,0.667149,0.698043,0.774352,0.331903,0.431558,0.297913,0.199821,0.422575,0.268204,0.932195,0.947315,0.006675,0.083064
63,0.351778,0.269632,0.221999,0.069622,0.833638,0.820387,0.209593,0.620300,0.078368,0.976198,0.029155,0.991013,0.550583,0.963815,0.217475,0.407626,0.159348,0.849669,0.313237,0.613734,0.212551,0.418758,0.201668,0.396545,0.830362
64,0.805075,0.001671,0.195332,0.027470,0.608216,0.628619,0.864247,0.697748,0.589667,0.097371,0.018456,0.484583,0.166702,0.150403,0.942255,0.691582,0.277676,0.664905,0.955523,0.537096,0.395565,0.854805,0.004526,0.918757,0.140045
65,0.107759,0.413028,0.217406,0.544030,0.689717,0.190146,0.653640,0.427461,0.507305,0.857113,0.577745,0.049157,0.395093,0.791955,0.326743,0.038641,0.978361,0.923954,0.801451,0.583916,0.208752,0.684703,0.344855,0.767579,0.919771
66,0.755190,0.559257,0.459835,0.333651,0.508843,0.592598,0.043635,0.556885,0.021932,0.115954,0.690496,0.868134,0.197210,0.003514,0.757946,0.696139,0.784404,0.995170,0.774996,0.785716,0.910667,0.320033,0.577368,0.812964,0.857915
67,0.530904,0.884259,0.514139,0.724375,0.689304,0.612350,0.635729,0.236790,0.978424,0.297528,0.921894,0.585537,0.219434,0.106993,0.328263,0.006024,0.107397,0.148467,0.557860,0.298733,0.796115,0.632579,0.889644,0.501292,0.670639
68,0.300622,0.276355,0.763328,0.664808,0.344841,0.774585,0.912690,0.800142,0.535074,0.436897,0.825940,0.355634,0.489028,0.139880,0.187032,0.318337,0.240613,0.854656,0.251985,0.133727,0.971153,0.219264,0.711315,0.401607,0.529178
69,0.372270,0.230964,0.835252,0.745290,0.183172,0.519750,0.983784,0.744055,0.627540,0.081655,0.984668,0.978259,0.327747,0.893184,0.199878,0.622013,0.040779,0.344331,0.278874,0.071870,0.764543,0.422831,0.621159,0.623135,0.001385
70,0.896071,0.068191,0.825584,0.945009,0.264674,0.492006,0.753109,0.832198,0.060738,0.133384,0.920725,0.246139,0.079725,0.521544,0.130722,0.122232,0.471167,0.271127,0.318770,0.121010,0.392625,0.717247,0.507943,0.545796,0.616721
71,0.885058,0.248684,0.318268,0.314120,0.046474,0.553614,0.643206,0.226195,0.210880,0.278404,0.091422,0.775025,0.801413,0.042123,0.381139,0.490984,0.811206,0.362155,0.554944,0.239554,0.122965,0.059272,0.695450,0.136427,0.055553
72,0.992951,0.109286,0.284777,0.322499,0.636183,0.741985,0.769288,0.692446,0.489585,0.199704,0.391130,0.347166,0.263309,0.311742,0.046245,0.172696,0.456198,0.490771,0.069177,0.262140,0.092017,0.058004,0.795942,0.030991,0.068966
73,0.294493,0.342998,0.220630,0.273316,0.434656,0.940819,0.137694,0.403842,0.329504,0.775234,0.830886,0.203939,0.849741,0.145734,0.359307,0.863162,0.133555,0.301641,0.849980,0.824676,0.838902,0.827671,0.528109,0.858377,0.746602
74,0.122606,0.006844,0.029144,0.912405,0.510479,0.206442,0.669547,0.496610,0.279585,0.767388,0.961327,0.090758,0.824918,0.524127,0.807243,0.436374,0.966226,0.807370,0.343491,0.328836,0.532846,0.793287,0.383970,0.281262,0.388998
75,0.357231,0.382885,0.118024,0.856791,0.989116,0.191424,0.881895,0.453529,0.067095,0.118315,0.890707,0.899166,0.109955,0.180989,0.520770,0.152527,0.833017,0.509071,0.910202,0.192544,0.674794,0.696041,0.906813,0.278967,0.826986
76,0.739354,0.908009,0.235795,0.864357,0.793935,0.706433,0.132950,0.189824,0.213989,0.842326,0.731375,0.093444,0.513128,0.817881,0.882441,0.883842,0.673366,0.752532,0.378626,0.703574,0.583908,0.515323,0.525852,0.727062,0.829348
77,0.878578,0.939046,0.233515,0.168353,0.005751,0.844289,0.762197,0.611552,0.137437,0.169299,0.140702,0.594544,0.713317,0.937929,0.543468,0.245753,0.962640,0.594573,0.785001,0.121736,0.275101,0.018166,0.135647,0.846175,0.923001
78,0.293614,0.139052,0.766652,0.626661,0.140010,0.947558,0.055875,0.689056,0.212521,0.228825,0.734593,0.638676,0.844571,0.344616,0.034610,0.347852,0.974417,0.062188,0.248804,0.976016,0.615959,0.955550,0.002685,0.872718,0.020206
79,0.094674,0.049637,0.342380,0.505690,0.640615,0.399815,0.100706,0.806437,0.252407,0.551043,0.600520,0.518124,0.342736,0.986924,0.272423,0.503648,0.803858,0.819921,0.935994,0.783499,0.904277,0.819510,0.711470,0.812452,0.069051
80,0.054719,0.666023,0.658276,0.119491,0.951287,0.160978,0.634333,0.310460,0.109686,0.412321,0.951291,0.189900,0.010464,0.175621,0.036660,0.795070,0.822805,0.306339,0.416792,0.947824,0.874446,0.128344,0.341579,0.914923,0.210012
81,0.186464,0.768803,0.310152,0.579320,0.833768,0.948224,0.299606,0.383300,0.034717,0.091810,0.358612,0.534083,0.348873,0.032821,0.128339,0.187685,0.167562,0.310689,0.464388,0.888444,0.753207,0.572476,0.890478,0.716289,0.476203
82,0.028722,0.966190,0.640988,0.988542,0.600844,0.963428,0.448832,0.639883,0.388605,0.026401,0.620671,0.622898,0.489559,0.429031,0.762136,0.292637,0.380171,0.230375,0.988635,0.147887,0.344793,0.193160,0.913385,0.097928,0.658875
83,0.939236,0.826082,0.544509,0.472419,0.194625,0.574121,0.883394,0.718795,0.273349,0.159481,0.716332,0.804830,0.035411,0.615725,0.941425,0.171592,0.004771,0.411328,0.606752,0.866677,0.297239,0.465709,0.698254,0.362999,0.773967
84,0.242640,0.155782,0.696014,0.092995,0.116702,0.735935,0.511798,0.249718,0.854870,0.562328,0.181525,0.946926,0.159335,0.500072,0.295638,0.252890,0.174743,0.266113,0.909589,0.365486,0.856863,0.701166,0.905132,0.702145,0.387421
85,0.514028,0.584117,0.889063,0.627150,0.574748,0.242815,0.650442,0.644591,0.124973,0.103530,0.471121,0.555962,0.998552,0.482873,0.873771,0.485500,0.579112,0.371919,0.460597,0.858602,0.833965,0.572732,0.340594,0.690563,0.830677
86,0.062960,0.739992,0.977503,0.824442,0.313270,0.731586,0.424769,0.250265,0.533736,0.424395,0.805781,0.837279,0.235620,0.723413,0.958931,0.264992,0.218579,0.111794,0.764747,0.382467,0.619979,0.847642,0.611316,0.956707,0.586305

In [71]:
pd.reset_option("all")  # volta tudo para a configuração que padrão

C:\Users\luiz_\AppData\Local\Temp\ipykernel_4040\3062228216.py:1: FutureWarning: data_manager option is deprecated and will be removed in a future version. Only the BlockManager will be available.
  pd.reset_option("all")  # volta tudo para a configuração que padrão
C:\Users\luiz_\AppData\Local\Temp\ipykernel_4040\3062228216.py:1: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option("all")  # volta tudo para a configuração que padrão

In [72]:
df

,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,...,col_16,col_17,col_18,col_19,col_20,col_21,col_22,col_23,col_24,col_25
0,0.098456,0.535637,0.458692,0.868133,0.159866,0.068098,0.013720,0.552712,0.773944,0.130788,...,0.363725,0.014331,0.145128,0.900499,0.154200,0.862587,0.714738,0.500876,0.893423,0.827683
1,0.666551,0.199129,0.113908,0.210120,0.906292,0.705294,0.088237,0.258326,0.939174,0.540132,...,0.839374,0.272497,0.036057,0.093916,0.438405,0.282779,0.954644,0.788169,0.177984,0.453759
2,0.656975,0.755802,0.061194,0.709328,0.790547,0.920393,0.785355,0.933094,0.031755,0.430484,...,0.691620,0.695630,0.329219,0.936155,0.942365,0.626486,0.152185,0.853133,0.301353,0.318562
3,0.189837,0.673615,0.065945,0.664920,0.021058,0.919143,0.675001,0.739302,0.566167,0.819979,...,0.382811,0.553252,0.573448,0.709384,0.915707,0.947968,0.993401,0.958356,0.480183,0.712311
4,0.230764,0.597503,0.302457,0.346512,0.059277,0.446300,0.128191,0.044563,0.633335,0.805341,...,0.387274,0.506204,0.621079,0.266936,0.883223,0.029511,0.311366,0.528980,0.841551,0.775268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.169252,0.437056,0.842609,0.502365,0.893767,0.663994,0.849268,0.972514,0.392392,0.253170,...,0.729770,0.365280,0.633781,0.633033,0.260729,0.578339,0.028964,0.280884,0.988434,0.510529
96,0.040020,0.516046,0.055658,0.767621,0.174608,0.001090,0.251764,0.252084,0.961006,0.328676,...,0.835476,0.068663,0.891048,0.785781,0.331233,0.112352,0.279274,0.387005,0.792598,0.962871
97,0.754221,0.967325,0.657335,0.572218,0.653453,0.044631,0.462014,0.634968,0.174108,0.381411,...,0.348017,0.273670,0.234118,0.771742,0.073964,0.678563,0.594324,0.637076,0.158399,0.039755
98,0.550514,0.538025,0.485677,0.169086,0.785028,0.924552,0.920987,0.139113,0.526103,0.407765,...,0.369034,0.494541,0.682738,0.175663,0.572211,0.997730,0.869203,0.252710,0.743849,0.671129
99,0.936135,0.575452,0.359987,0.604559,0.944365,0.335257,0.485124,0.827429,0.823342,0.134752,...,0.653401,0.800621,0.560028,0.906782,0.769257,0.968024,0.702719,0.538291,0.157289,0.747574